# Generated by Django 5.0.4 on 2026-03-23 07:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('accession_number', models.CharField(max_length=100, unique=True)),
                ('order_id', models.CharField(max_length=255)),
                ('patient_id', models.CharField(max_length=255)),
                ('specimen_type', models.CharField(choices=[('blood', 'Blood'), ('urine', 'Urine'), ('serum', 'Serum'), ('plasma', 'Plasma'), ('saliva', 'Saliva'), ('tissue', 'Tissue'), ('stool', 'Stool'), ('csf', 'Cerebrospinal Fluid')], max_length=50)),
                ('collection_method', models.CharField(choices=[('venipuncture', 'Venipuncture'), ('capillary', 'Capillary'), ('clean_catch', 'Clean Catch'), ('needle_aspiration', 'Needle Aspiration'), ('biopsy', 'Biopsy')], max_length=50)),
                ('collection_time', models.DateTimeField()),
                ('received_time', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_unit', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('collected', 'Collected'), ('processing', 'Processing'), ('analyzed', 'Analyzed'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='collected', max_length=50)),
                ('collector_id', models.CharField(blank=True, max_length=255, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'specimens',
                'ordering': ['-collection_time'],
            },
        ),
        migrations.AddField(
            model_name='labresult',
            name='abnormal_flag',
            field=models.CharField(choices=[('N', 'Normal'), ('L', 'Low'), ('H', 'High'), ('LL', 'Critical Low'), ('HH', 'Critical High')], default='N', max_length=5),
        ),
        migrations.AddField(
            model_name='labresult',
            name='analyzer_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='labresult',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='labresult',
            name='reference_range_high',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='labresult',
            name='reference_range_low',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='labresult',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('verified', 'Verified'), ('preliminary', 'Preliminary'), ('amended', 'Amended'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='labresult',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labresult',
            name='verified_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CriticalValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(max_length=255)),
                ('test_name', models.CharField(max_length=255)),
                ('critical_value', models.CharField(max_length=500)),
                ('priority', models.CharField(choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], default='high', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('acted_upon', 'Acted Upon'), ('resolved', 'Resolved')], default='new', max_length=50)),
                ('reported_to', models.CharField(blank=True, max_length=255, null=True)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.CharField(blank=True, max_length=255, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('action_taken', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='critical_value', to='lab.labresult')),
            ],
            options={
                'db_table': 'critical_values',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=255, unique=True)),
                ('patient_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('preliminary', 'Preliminary'), ('final', 'Final'), ('corrected', 'Corrected'), ('cancelled', 'Cancelled')], default='draft', max_length=50)),
                ('report_number', models.CharField(max_length=100, unique=True)),
                ('generated_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.CharField(max_length=255)),
                ('verified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('interpretation', models.TextField(blank=True)),
                ('critical_values_count', models.IntegerField(default=0)),
                ('attachments', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lab.specimen')),
            ],
            options={
                'db_table': 'lab_reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyzerQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('analyzer_id', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('stat', 'STAT'), ('priority', 'Priority')], default='routine', max_length=50)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('retry', 'Retry')], default='queued', max_length=50)),
                ('position_in_queue', models.IntegerField()),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.specimen')),
            ],
            options={
                'db_table': 'analyzer_queue',
                'ordering': ['priority', 'position_in_queue'],
            },
        ),
        migrations.AddField(
            model_name='labresult',
            name='specimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='lab.specimen'),
        ),
    ]
