# Generated by Django 5.0.4 on 2026-03-30 19:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_specimen_labresult_abnormal_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimen',
            name='condition',
            field=models.CharField(blank=True, choices=[('acceptable', 'Acceptable'), ('hemolyzed', 'Hemolyzed'), ('lipemic', 'Lipemic'), ('icteric', 'Icteric'), ('clotted', 'Clotted'), ('insufficient', 'Insufficient'), ('wrong_tube', 'Wrong Tube')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('collected', 'Collected'), ('in_transit', 'In Transit'), ('received', 'Received'), ('processing', 'Processing'), ('analyzed', 'Analyzed'), ('resulted', 'Resulted'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='collected', max_length=50),
        ),
        migrations.CreateModel(
            name='RecollectionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('collected', 'Collected'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recollection_requests', to='lab.specimen')),
            ],
            options={
                'db_table': 'specimen_recollection_requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
