# Generated by Django 5.0.4 on 2026-04-12 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_specimen_condition_alter_specimen_status_and_more'),
        ('patients', '0002_encounter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laborder',
            name='encounter_id',
        ),
        migrations.RemoveField(
            model_name='laborder',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='labreport',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='labreport',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='specimen',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='specimen',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='criticalvalue',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='laborder',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laborder',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='patients.encounter'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='labreport',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labreport',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_reports', to='patients.encounter'),
        ),
        migrations.AddField(
            model_name='labreport',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report', to='lab.laborder'),
        ),
        migrations.AddField(
            model_name='labreport',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_reports', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='labreport',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labresult',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labresult',
            name='correction_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='lab.labresult'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_results', to='patients.encounter'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='specimen',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specimens', to='patients.encounter'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specimens', to='lab.laborder'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specimens', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='received_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
