# Generated by Django 5.0.4 on 2026-04-12 12:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingstats',
            options={'ordering': ['-month'], 'verbose_name': 'Billing stats', 'verbose_name_plural': 'Billing stats'},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='encounter_id',
        ),
        migrations.RemoveField(
            model_name='patientaccount',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='claimdenial',
            name='appeal_status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='claimdenial',
            name='appealed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimdenial',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimdenial',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='claimdenial',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialtimeline',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='eob_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='last_resubmitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='resubmission_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
