# Generated by Django 5.0.4 on 2026-04-12 12:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_billingstats_options_and_more'),
        ('hospital_administration', '0007_alter_bed_bed_number_bedassignment'),
        ('patients', '0002_encounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='patients.encounter'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='cpt_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='icd10_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='lab_catalog_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_line_items', to='hospital_administration.labcatalogitem'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='provider',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='radiology_catalog_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_line_items', to='hospital_administration.radiologycatalogitem'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='service_catalog_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_line_items', to='hospital_administration.servicecatalogitem'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='service_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='source_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='source_type',
            field=models.CharField(choices=[('lab', 'Laboratory'), ('radiology', 'Radiology'), ('service', 'Service'), ('bed', 'Bed Assignment'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='patientaccount',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientaccount',
            name='patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_account', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='payment',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='financialtimeline',
            name='transaction_type',
            field=models.CharField(choices=[('invoice', 'Invoice Issued'), ('payment', 'Payment Received'), ('adjustment', 'Adjustment'), ('refund', 'Refund'), ('claim_approval', 'Claim Approved'), ('claim_denial', 'Claim Denied'), ('collection', 'Collection Action'), ('invoice_voided', 'Invoice Voided'), ('claim_submitted', 'Claim Submitted'), ('claim_paid', 'Claim Paid')], max_length=50),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('appealed', 'Appealed'), ('resubmitted', 'Resubmitted')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('partially_paid', 'Partially Paid'), ('fully_paid', 'Fully Paid'), ('overdue', 'Overdue'), ('void', 'Void'), ('cancelled', 'Cancelled')], default='draft', max_length=50),
        ),
    ]
