# Generated by Django 5.0.4 on 2026-04-12 14:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_encounter_invoice_voided_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('charge', 'Charge'), ('payment', 'Payment'), ('adjustment', 'Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reference_id', models.CharField(db_index=True, max_length=255)),
                ('created_by', models.CharField(blank=True, default='system', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_transactions', to='billing.patientaccount')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_transactions', to='billing.invoice')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_transactions', to='billing.payment')),
            ],
            options={
                'db_table': 'billing_transactions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['account', 'timestamp'], name='billing_tra_account_3b612f_idx'), models.Index(fields=['type', 'timestamp'], name='billing_tra_type_598106_idx')],
            },
        ),
    ]
