# Generated by Django 5.0.4 on 2026-04-12 14:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(db_index=True, max_length=150)),
                ('delivery_group', models.CharField(db_index=True, max_length=150)),
                ('reference_id', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('retrying', 'Retrying'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('last_error', models.TextField(blank=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shared_notification_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_id', models.CharField(blank=True, default='anonymous', max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('request_hash', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('response_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shared_idempotency_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['path', 'created_at'], name='shared_idem_path_348bf7_idx'), models.Index(fields=['status', 'created_at'], name='shared_idem_status_7971a2_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='idempotencyrecord',
            constraint=models.UniqueConstraint(fields=('actor_id', 'key', 'method', 'path'), name='uq_idempotency_actor_key_method_path'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status', 'next_retry_at'], name='shared_noti_status_3fb29b_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['event_name', 'created_at'], name='shared_noti_event_n_30ba3d_idx'),
        ),
    ]
