# Generated by Django 5.0.4 on 2026-03-23 07:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('head_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('module', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'permissions',
                'ordering': ['module', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('actor_id', models.CharField(max_length=255)),
                ('actor_role', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('permission_change', 'Permission Change'), ('role_assignment', 'Role Assignment')], max_length=50)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['actor_id', '-timestamp'], name='audit_logs_actor_i_9ecce2_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_logs_entity__d4c2e5_idx'), models.Index(fields=['action', '-timestamp'], name='audit_logs_action_f48619_idx')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_system_role', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(related_name='roles', to='hospital_administration.permission')),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('general', 'General Ward'), ('icu', 'ICU'), ('pediatric', 'Pediatric'), ('maternity', 'Maternity'), ('orthopedic', 'Orthopedic'), ('cardiac', 'Cardiac')], max_length=50)),
                ('total_beds', models.IntegerField()),
                ('available_beds', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('closed', 'Closed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital_administration.department')),
            ],
            options={
                'db_table': 'wards',
                'ordering': ['name'],
                'unique_together': {('department', 'code')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.CharField(max_length=255)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital_administration.role')),
            ],
            options={
                'db_table': 'user_roles',
                'unique_together': {('user_id', 'role')},
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('bed_number', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('standard', 'Standard'), ('private', 'Private'), ('icu', 'ICU'), ('pediatric', 'Pediatric')], max_length=50)),
                ('features', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance'), ('reserved', 'Reserved')], default='available', max_length=20)),
                ('patient_id', models.CharField(blank=True, max_length=255, null=True)),
                ('occupied_since', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='hospital_administration.ward')),
            ],
            options={
                'db_table': 'beds',
                'ordering': ['bed_number'],
                'unique_together': {('ward', 'bed_number')},
            },
        ),
    ]
