# Generated by Django 5.0.4 on 2026-03-30 19:44

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_administration', '0002_department_permission_systemsettings_auditlog_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabCatalogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('specimen_type', models.CharField(choices=[('blood', 'Blood'), ('urine', 'Urine'), ('serum', 'Serum'), ('plasma', 'Plasma'), ('saliva', 'Saliva'), ('tissue', 'Tissue'), ('stool', 'Stool'), ('csf', 'Cerebrospinal Fluid'), ('other', 'Other')], default='blood', max_length=20)),
                ('default_unit', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lab_catalog_items',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RadiologyCatalogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('modality', models.CharField(choices=[('xray', 'X-Ray'), ('ct', 'CT'), ('mri', 'MRI'), ('ultrasound', 'Ultrasound'), ('nuclear', 'Nuclear Medicine'), ('other', 'Other')], default='xray', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'radiology_catalog_items',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCatalogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('consultation', 'Consultation'), ('procedure', 'Procedure'), ('room', 'Room/Bed'), ('nursing', 'Nursing'), ('other', 'Other')], default='consultation', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'service_catalog_items',
                'ordering': ['code'],
            },
        ),
    ]
