# Generated by Django 5.0.4 on 2026-03-31 12:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_administration', '0004_rename_auditlog_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-occurred_at']},
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_logs_actor_i_9ecce2_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_logs_action_f48619_idx',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='outcome',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('failure', 'Failure'), ('warning', 'Warning'), ('info', 'Info')], default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='source_module',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bed',
            name='bed_class',
            field=models.CharField(choices=[('general', 'General'), ('private', 'Private'), ('isolation', 'Isolation'), ('critical_care', 'Critical Care'), ('newborn', 'Newborn')], default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='bed',
            name='blocked_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bed',
            name='cleaning_status',
            field=models.CharField(choices=[('clean', 'Clean'), ('needs_cleaning', 'Needs Cleaning'), ('cleaning_in_progress', 'Cleaning In Progress'), ('sanitized', 'Sanitized')], default='clean', max_length=30),
        ),
        migrations.AddField(
            model_name='bed',
            name='room_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='department',
            name='department_type',
            field=models.CharField(choices=[('inpatient', 'Inpatient'), ('outpatient', 'Outpatient'), ('radiology', 'Radiology'), ('nursery', 'Nursery'), ('laboratory', 'Laboratory'), ('pharmacy', 'Pharmacy'), ('billing', 'Billing'), ('administration', 'Administration')], default='administration', max_length=30),
        ),
        migrations.AddField(
            model_name='department',
            name='extension_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='department',
            name='floor',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='department',
            name='is_clinical',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='department',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='department',
            name='manager_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='department',
            name='operating_hours',
            field=models.CharField(blank=True, default='24/7', max_length=100),
        ),
        migrations.AddField(
            model_name='labcatalogitem',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_catalog_items', to='hospital_administration.department'),
        ),
        migrations.AddField(
            model_name='labcatalogitem',
            name='fasting_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labcatalogitem',
            name='minimum_volume_ml',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='labcatalogitem',
            name='processing_site',
            field=models.CharField(choices=[('in_house', 'In House'), ('outsource', 'Outsource')], default='in_house', max_length=20),
        ),
        migrations.AddField(
            model_name='labcatalogitem',
            name='sample_container',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='labcatalogitem',
            name='stat_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='labcatalogitem',
            name='turnaround_time_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='permission',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('assign', 'Assign'), ('configure', 'Configure'), ('export', 'Export'), ('manage', 'Manage')], default='view', max_length=20),
        ),
        migrations.AddField(
            model_name='permission',
            name='is_sensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='scope',
            field=models.CharField(default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='radiologycatalogitem',
            name='body_part',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='radiologycatalogitem',
            name='contrast_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='radiologycatalogitem',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='radiology_catalog_items', to='hospital_administration.department'),
        ),
        migrations.AddField(
            model_name='radiologycatalogitem',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='radiologycatalogitem',
            name='preparation_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='radiologycatalogitem',
            name='report_turnaround_minutes',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='radiologycatalogitem',
            name='sedation_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='radiologycatalogitem',
            name='uses_radiation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role',
            name='category',
            field=models.CharField(choices=[('system', 'System'), ('administration', 'Administration'), ('clinical', 'Clinical'), ('operations', 'Operations'), ('revenue_cycle', 'Revenue Cycle')], default='administration', max_length=30),
        ),
        migrations.AddField(
            model_name='role',
            name='is_assignable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicecatalogitem',
            name='billing_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('per_occurrence', 'Per Occurrence'), ('per_day', 'Per Day'), ('package', 'Package')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='servicecatalogitem',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_catalog_items', to='hospital_administration.department'),
        ),
        migrations.AddField(
            model_name='servicecatalogitem',
            name='insurance_category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='servicecatalogitem',
            name='package_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicecatalogitem',
            name='service_duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='category',
            field=models.CharField(choices=[('hospital_profile', 'Hospital Profile'), ('bed_management', 'Bed Management'), ('billing', 'Billing'), ('security', 'Security'), ('notifications', 'Notifications'), ('integrations', 'Integrations'), ('operations', 'Operations')], default='operations', max_length=30),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='data_type',
            field=models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='is_sensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrole',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrole',
            name='scope_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_roles', to='hospital_administration.department'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='scope_ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_roles', to='hospital_administration.ward'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='ward',
            name='age_group',
            field=models.CharField(choices=[('mixed', 'Mixed'), ('adult', 'Adult'), ('pediatric', 'Pediatric'), ('neonatal', 'Neonatal')], default='mixed', max_length=20),
        ),
        migrations.AddField(
            model_name='ward',
            name='gender_restriction',
            field=models.CharField(choices=[('mixed', 'Mixed'), ('male', 'Male'), ('female', 'Female')], default='mixed', max_length=10),
        ),
        migrations.AddField(
            model_name='ward',
            name='nurse_station',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ward',
            name='specialty',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ward',
            name='supports_isolation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_id',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='occurred_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='bed',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Maintenance'), ('cleaning', 'Cleaning'), ('blocked', 'Blocked')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='bed',
            name='type',
            field=models.CharField(choices=[('standard', 'Standard'), ('private', 'Private'), ('icu', 'ICU'), ('pediatric', 'Pediatric'), ('incubator', 'Incubator')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ward',
            name='type',
            field=models.CharField(choices=[('general', 'General Ward'), ('icu', 'ICU'), ('pediatric', 'Pediatric'), ('maternity', 'Maternity'), ('nursery', 'Nursery'), ('observation', 'Observation'), ('isolation', 'Isolation')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor_id', '-occurred_at'], name='audit_logs_actor_i_7045a7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-occurred_at'], name='audit_logs_action_f340dc_idx'),
        ),
    ]
