# Generated by Codex on 2026-03-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital_administration", "0005_alter_auditlog_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecatalogitem",
            name="requires_bed_assignment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="servicecatalogitem",
            name="requires_physician_order",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="servicecatalogitem",
            name="requires_result_entry",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="servicecatalogitem",
            name="revenue_code",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="servicecatalogitem",
            name="service_class",
            field=models.CharField(
                choices=[
                    ("clinical", "Clinical"),
                    ("diagnostic", "Diagnostic"),
                    ("room_and_board", "Room And Board"),
                    ("administrative", "Administrative"),
                ],
                default="clinical",
                max_length=30,
            ),
        ),
    ]
