# Generated by Django 5.0.4 on 2026-04-12 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_administration', '0007_alter_bed_bed_number_bedassignment'),
        ('patients', '0002_encounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedassignment',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bed_assignments', to='patients.encounter'),
        ),
        migrations.AddField(
            model_name='bedassignment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bed_assignments', to='patients.patient'),
        ),
        migrations.AddIndex(
            model_name='bedassignment',
            index=models.Index(fields=['bed', 'status'], name='bed_assignm_bed_id_59cd1c_idx'),
        ),
        migrations.AddIndex(
            model_name='bedassignment',
            index=models.Index(fields=['patient', 'status'], name='bed_assignm_patient_6868de_idx'),
        ),
        migrations.AddIndex(
            model_name='bedassignment',
            index=models.Index(fields=['encounter', 'status'], name='bed_assignm_encount_9e7894_idx'),
        ),
    ]
