# Generated by Django 5.0.4 on 2026-03-21 17:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'auth_user',
                'indexes': [models.Index(fields=['email'], name='auth_user_email_ece7f7_idx'), models.Index(fields=['is_active'], name='auth_user_is_acti_9dcf31_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('refresh_token', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('token_type', models.CharField(choices=[('Bearer', 'Bearer'), ('Basic', 'Basic')], default='Bearer', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_token',
                'indexes': [models.Index(fields=['access_token'], name='auth_token_access__9de43e_idx'), models.Index(fields=['user', 'is_valid'], name='auth_token_user_id_451130_idx'), models.Index(fields=['expires_at'], name='auth_token_expires_7c1494_idx')],
            },
        ),
    ]
