# Generated by Django 5.0.4 on 2026-04-12 12:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_administration', '0007_alter_bed_bed_number_bedassignment'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('OP', 'Outpatient'), ('IP', 'Inpatient'), ('ER', 'Emergency')], max_length=2)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('discharged', 'Discharged')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='hospital_administration.department')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='patients.patient')),
            ],
            options={
                'db_table': 'encounters',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['patient', 'status'], name='encounters_patient_6402a8_idx'), models.Index(fields=['department', 'status'], name='encounters_departm_00058e_idx'), models.Index(fields=['doctor', 'status'], name='encounters_doctor__1fd89f_idx')],
            },
        ),
    ]
